url=http://www.byndr.com
signin=//a[text()='Sign In']
username=//input[@type='username']
pswd=//input[@type='password']
login=//button[@type='submit']

searchBar=//input[@id='header-search-input']
searchResult=//ul[@class='isearch-results']/li

message=//label[text()='Messages']
to=//a[text()='Entire Institution ']
demo=//li[text()='Demo']
all=//li[text()='All Students and Faculty']
select1=//button[text()='Select']
text=//textarea[@name='textarea']
addmaterial=//material-selector[@class='ng-scope ng-isolate-scope']
upload=//ul[@class='material-add-list']/li
filepath=D:\\webdriver\\autoIT\\testfile1.exe
review=//button[@type='submit' and text() ='Review Message']
send=//button[text()='Send Message']

#  Profile details
openProfile=//img[@class='inst_logo ng-scope']
signout=//a[text()='sign out']

profile=//div[@class='user-thumb']/div[1]
settings=//a[text()='Settings']
profileName=//div[@class='modal-body-inner-wrap']/div/ul/li[1]/div[2]
profileEmail=//div[@class='modal-body-inner-wrap']/div/ul/li[2]/div[2]
profilePhone=//div[@class='modal-body-inner-wrap']/div/ul/li[4]/div[2]

#I want to list
addstudent=//*[text()='Add a Student']
addfaculty=//*[@id='teacherActionList']/ul/a[2]
addcourse=//div[text()='Add a Course']

# Add student and faculty
fullname=//input[@name='display_name']
email=//input[@name='email']
password= //input[@name='password']
phone=//input[@name='phone']
prntPhn=//ul[@class='stretch-list']/li[5]/ol/li[2]/input
id=//input[@name='regn']
department=//li[@class='sl-value']/select
select3=//li[@class='sl-value']/select/option[2]
programLabel=//li[text()='Program']
program=//select[@name='form_programs']
select4=//select[@name='form_programs']/option[2]
yearLabel=//li[text()='Year']
year=//select[@name='form_years']
select5=//select[@name='form_years']/option[3]
sectionLabel=//li[text()='Section']
sectionA=//select/option[text()='Section A']
save=//button[text()='Save']
cancel=//a[text()='Cancel']
cancelButton=//button[text()='Cancel']
yesDiscard=//button[text()='Yes, Discard Changes']

#About Student
studentName=//ul[@class='stretch-list']/li[1]/ol/li[2]/span
studentEmail=//ul[@class='stretch-list']/li[2]/ol/li[2]/span
studentPhn=//ul[@class='stretch-list']/li[3]/ol/li[2]/span
studentId=//ul[@class='stretch-list']/li[4]/ol/li[2]/span
studentDepartment=//ul[@class='stretch-list']/li[5]/ol/li[2]/span
studentPrntPhn=//ul[@class='stretch-list']/li[6]/ol/li[2]/span
studentProgram=//ul[@class='stretch-list']/li[9]/ol/li[2]/div/span
studentYear=//ul[@class='stretch-list']/li[10]/ol/li[2]/div/span
studentSection=//ul[@class='stretch-list']/li[11]/ol/li[2]/div/span

#About faculty
teacherName=//ul[@class='stretch-list']/li[1]/ol/li[2]/span
teacherEmail=//ul[@class='stretch-list']/li[2]/ol/li[2]/span
teacherPhn=//ul[@class='stretch-list']/li[3]/ol/li[2]/span

#Department selections

departments=//a[@href='#/departments/']
demo1=//li[@href='#/departments/Demo']
programs=//li[@href='#/departments/Demo/Demo']
years=//div[text()='Year II']

# list of courses, students, faculty

panel-list-faculty=//div[@class='panel-list-heading-2']/h3[4]
facultyCount=//div[@class='panel-list-heading-2']/h3[4]/span
panel-list-student=//div[@class='panel-list-heading-2']/h3[3]
studentCount=//div[@class='panel-list-heading-2']/h3[3]/span 
listCount1=//div[@id='courseList']/ul/li[
listCount2=]
courseCount=//div[@class='panel-list-heading-2']/h3[2]/span

#attendance
courses=//div[text()='C++ Programming']
attendance=//div[text()='Attendance Summary']
date=//*[@id='grade-values-header-wrap']/th[5]/div[1]/div
student1=//ul[@class='entries ng-isolate-scope']/li[1]/div[3]/label
student2=//ul[@class='entries ng-isolate-scope']/li[3]/div[3]/label
student3=//ul[@class='entries ng-isolate-scope']/li[5]/div[3]/label

#add Course
courseName=//input[@name='course_name']
courseDescription=//li[text()='Description']/following-sibling::li/input
courseAcademy=//input[@name='term']
courseFaculty=//ul[@class='stretch-list']/li[8]/ol/li[2]/a
search=//input[@class='ng-pristine ng-untouched ng-valid ng-empty']
selectFaculty=//ul[@class='entries']/li[2]
selectedFaculty=//li[@class='user ng-isolate-scope']
#studentLabel=//li[text()='Students ']
courseStudent=//ul[@class='stretch-list']/li[9]/ol/li[2]/a
selectStudent=//ul[@class='entries']/li[2]
selectedStudent=//label[@class='name ng-binding']

#About course
ccourseName=//ul[@class='stretch-list']/li[1]/ol/li[2]/span
cdescription=//ul[@class='stretch-list']/li[2]/ol/li[2]/span
cdepartment=//ul[@class='stretch-list']/li[3]/ol/li[2]/span
cprogram=//ul[@class='stretch-list']/li[4]/ol/li[2]/span
cyear=//ul[@class='stretch-list']/li[5]/ol/li[2]/span
csection=//ul[@class='stretch-list']/li[6]/ol/li[2]/span
cacademy=//ul[@class='stretch-list']/li[7]/ol/li[2]/span
cfaculty=//ul[@class='stretch-list']/li[8]/ol/li[2]
cstudentCount=//div[@class='stretch-list-wrap ng-scope']/ul/li[9]/ol/li/span
cstudentNames1=//ul[@class='stretch-list']/li[9]/ol/li[2]/ul/li[
cstudentNames2=]/a/label
viewPage=//div[text()='View Course Page']

allStudents=//ul[@class='user-form-input']







							#  Inputs
homeTitle=Home - Byndr

# admin credentials
admin_userid=satish_admin
admin_pswd=password						

# teacher credentials
teacher_userid=
teacher_pswd=

#student credentials
student_userid=
student_pswd=

# add faculty

teacher_name=praneeth
teacher_email=praneethPA@test.com
teacher_password=byndr1234
teacher_phone=0987654321
	
# add student 

student_Name=venu
student_Email=venuPA@test.com
student_Password=byndr1234
student_Phone=0987637897
student_PrntPhn=0964859584
student_ID=0933837

#add course
course_name=circuit-system
course_description=Circuit-systems
course_academy=2019-2020